### ISSUE TITLE
[OpenShift 3.11] Console returns 500 internal error when configured with custom certificate

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#4704]
**Describe the bug**
On OpenShift 3.11 (v3.11.154), the console proxy (oauth-proxy) will fail to trust the oauth authorization URL service certificate if it is not signed by the OpenShift cluster CA. This regression is caused by #4305 , and reverting to an image of the controller-manager before this revision resolves the issue.

My theory is that #4305 causes the 'system CA' to no longer be trusted, so there is no verifiable chain to the custom certificate.

**To Reproduce**
Steps to reproduce the behavior (Not verified, but probable):
1. Install OpenShift 3.11 with an API certificate that is signed by a public Root CA and not the OpenShift Cluster CA
2. Install EnMasse 0.31.2
3. Observe 500 error when logging into console

**Expected behavior**
Console should be working

**Screenshots**

![image](https://user-images.githubusercontent.com/19670/84117378-b9782680-aa31-11ea-84cd-a1002ee568d3.png)

**Additional context**

From the oauth proxy log:

```
2020/06/08 14:23:59 oauthproxy.go:645: error redeeming code (client: NN): Post https://example.openshift.com/oauth/token:  x509: certificate signed by unknown authority
2020/06/08 14:23:59 oauthproxy.go:438: ErrorPage 500 Internal Error Internal Error
```

**Comment by k-wall** [comment]
Interesting on OCP 3.11 (v3.11.219) with an externally signed cert, we don't see this issue.  The trust appears automatically in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt of the console proxy pod.  

The Ansible inventory used to install this cluster looked like this:
```
openshift_master_named_certificates=[{"certfile": "/opt/cert.pem", "keyfile": "/opt/privkey.pem", "cafile": "/opt/chain.pem", "names": ["master.maas.xxxxx", "api.maas.xxxxx"]}]
```

I don't understand why the cluster (3.11.154) in the original report behaved differently.

I still think the change suggested by #4711 is valuable.
